Disable default features for git2 (ssh, https).
By default, git2 ships with ssh and https features enabled (which are
useless for commrate, as it does not use the network). This, in turn,
requires libssl and libcrypto, which are pretty heavy to load - the
lag is not huge, but is perceptible, especially when commrate fails
immediately (e.g. can not find the repository).

Compare the maximum startup time with libssl and libcrypto:

```
$ time commrate
error: could not find repository from '.'

real    0m0.032s
user    0m0.025s
sys     0m0.007s
```

and without these libs:

```
$ time commrate
error: could not find repository from '.'

real    0m0.004s
user    0m0.000s
sys     0m0.004s
```

The overall processing speed also seems to have some boost (up to 20%).